name: tf2-nlp
channels:
  - javascript
dependencies:
  - python=3.7   # or 2.7
  - bokeh
  - numpy
  - pandas
  - boto3
  - pip:    
    - beautifulsoup4==4.9.0
    - click==7.1.2
    - dask==2.16.0
    - Flask==1.1.2
    - h5py==2.10.0
    - holoviews==1.13.2
    - html5lib==1.0.1
    - ijson==2.6.1
    - imageio==2.8.0
    - ipykernel==5.1.4
    - ipython==7.13.0
    - ipywidgets==7.5.1
    - jupyter==1.0.0
    - lxml==4.5.0
    - nltk==3.4.5
    - numba==0.49.1
    - Pillow==7.1.2
    - protobuf==3.9.2
    - psutil==5.7.0
    - pyarrow==0.16.0
    - pylint==2.5.2
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - scikit-image==0.16.2
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - seaborn==0.10.1
    - six==1.14.0
    - SQLAlchemy==1.3.17
    - statsmodels==0.11.1
    - tensorflow==2.2.0
    - tqdm==4.46.0
    - ujson==1.35